In [1]:
print("ASG Airlines Data Engineering Project")

ASG Airlines Data Engineering Project

In [2]:
import pandas as pd

In [3]:
file_path = "../data/raw/UseCase - Airlines.xlsx"

In [4]:
excel_file = pd.ExcelFile(file_path)

excel_file.sheet_names

['flights', 'payments', 'bookings', 'passengers']

In [5]:
flights = pd.read_excel(file_path, sheet_name="flights")
bookings = pd.read_excel(file_path, sheet_name="bookings")
passengers = pd.read_excel(file_path, sheet_name="passengers")
payments = pd.read_excel(file_path, sheet_name="payments")

In [6]:
print("Flights:", flights.shape)
print("Bookings:", bookings.shape)
print("Passengers:", passengers.shape)
print("Payments:", payments.shape)

Flights: (1020, 7)
Bookings: (1000, 9)
Passengers: (1039, 9)
Payments: (1000, 4)

In [7]:
flights.head()

,flight_id,airline,source,destination,departure_time,arrival_time,duration
0,SJ010,SpiceJet,CCU,MAA,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701,02:54:00
1,AI155,Air India,BOM,CCU,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703,01:48:00
2,UK094,Vistara,BOM,CCU,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702,01:45:00
3,AI245,Air India,BOM,CCU,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704,02:36:00
4,AI192,Air India,MAA,BOM,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703,04:59:00

In [8]:
print("Flights:", flights.columns.tolist())
print("Bookings:", bookings.columns.tolist())
print("Passengers:", passengers.columns.tolist())
print("Payments:", payments.columns.tolist())

Flights: ['flight_id', 'airline', 'source', 'destination', 'departure_time', 'arrival_time', 'duration']
Bookings: ['booking_id', 'passenger_id', 'flight_id', 'booking_date', 'status', 'passport_number', 'seat_number', 'emergency_contact_name', 'emergency_contact_phone']
Passengers: ['passenger_id', 'first_name', 'last_name', 'age', 'gender', 'email', 'phone', 'aadhaar_id', 'date_of_birth']
Payments: ['payment_id', 'booking_id', 'amount', 'payment_method']

In [9]:
print("FLIGHTS")
print(flights.columns.tolist())

print("\nBOOKINGS")
print(bookings.columns.tolist())

print("\nPASSENGERS")
print(passengers.columns.tolist())

print("\nPAYMENTS")
print(payments.columns.tolist())

FLIGHTS
['flight_id', 'airline', 'source', 'destination', 'departure_time', 'arrival_time', 'duration']

BOOKINGS
['booking_id', 'passenger_id', 'flight_id', 'booking_date', 'status', 'passport_number', 'seat_number', 'emergency_contact_name', 'emergency_contact_phone']

PASSENGERS
['passenger_id', 'first_name', 'last_name', 'age', 'gender', 'email', 'phone', 'aadhaar_id', 'date_of_birth']

PAYMENTS
['payment_id', 'booking_id', 'amount', 'payment_method']

In [10]:
flights.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   flight_id       1020 non-null   str
 1   airline         979 non-null    str
 2   source          1020 non-null   str
 3   destination     1020 non-null   str
 4   departure_time  1020 non-null   datetime64[us]
 5   arrival_time    1020 non-null   datetime64[us]
 6   duration        1020 non-null   object
dtypes: datetime64[us](2), object(1), str(4)
memory usage: 55.9+ KB

In [11]:
bookings.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   booking_id               1000 non-null   str
 1   passenger_id             1000 non-null   str
 2   flight_id                1000 non-null   str
 3   booking_date             1000 non-null   datetime64[us]
 4   status                   955 non-null    str
 5   passport_number          1000 non-null   str
 6   seat_number              1000 non-null   str
 7   emergency_contact_name   1000 non-null   str
 8   emergency_contact_phone  1000 non-null   str
dtypes: datetime64[us](1), str(8)
memory usage: 70.4 KB

In [12]:
passengers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1039 entries, 0 to 1038
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   passenger_id   1039 non-null   str
 1   first_name     1039 non-null   str
 2   last_name      1029 non-null   str
 3   age            1039 non-null   int64
 4   gender         1039 non-null   str
 5   email          1039 non-null   str
 6   phone          1039 non-null   str
 7   aadhaar_id     1039 non-null   int64
 8   date_of_birth  1039 non-null   datetime64[us]
dtypes: datetime64[us](1), int64(2), str(6)
memory usage: 73.2 KB

In [13]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      1000 non-null   str
 1   booking_id      1000 non-null   str
 2   amount          952 non-null    object
 3   payment_method  1000 non-null   str
dtypes: object(1), str(3)
memory usage: 31.4+ KB

In [14]:
flights.isnull().sum()

flight_id          0
airline           41
source             0
destination        0
departure_time     0
arrival_time       0
duration           0
dtype: int64

In [15]:
bookings.isnull().sum()

booking_id                  0
passenger_id                0
flight_id                   0
booking_date                0
status                     45
passport_number             0
seat_number                 0
emergency_contact_name      0
emergency_contact_phone     0
dtype: int64

In [16]:
passengers.isnull().sum()

passenger_id      0
first_name        0
last_name        10
age               0
gender            0
email             0
phone             0
aadhaar_id        0
date_of_birth     0
dtype: int64

In [18]:
payments.isnull().sum()

payment_id         0
booking_id         0
amount            48
payment_method     0
dtype: int64

In [19]:
flights.duplicated().sum()

np.int64(15)

In [20]:
bookings.duplicated().sum()

np.int64(0)

In [21]:
passengers.duplicated().sum()

np.int64(0)

In [22]:
payments.duplicated().sum()

np.int64(0)

In [25]:
flights["airline"].value_counts(dropna=False)

airline
IndiGo       249
SpiceJet     240
Air India    236
Vistara      223
NaN           41
UNKNOWN       31
Name: count, dtype: int64

In [26]:
bookings["status"].value_counts(dropna=False)

status
CONFIRMED    320
CANCELLED    314
PENDING      291
NaN           45
INVALID       30
Name: count, dtype: int64

In [27]:
flights["flight_id"].value_counts().head(20)

flight_id
AI242    2
SJ142    2
AI031    2
6F250    2
SJ146    2
UK163    2
AI020    2
SJ118    2
AI043    2
AI070    2
UK013    2
UK139    2
UK160    2
UK180    2
UK049    2
SJ037    2
SJ010    1
AI155    1
UK094    1
AI245    1
Name: count, dtype: int64

In [28]:
flights[flights["flight_id"].duplicated(keep=False)].sort_values("flight_id")

,flight_id,airline,source,destination,departure_time,arrival_time,duration
253,6F250,UNKNOWN,DEL,BLR,2026-04-20 03:26:41.701,2026-04-20 07:30:41.701,04:04:00
270,6F250,UNKNOWN,CCU,BLR,2026-04-20 02:23:41.702,2026-04-20 02:56:41.702,00:33:00
550,AI020,NaN,BOM,BLR,2026-04-19 03:53:41.701,2026-04-19 06:21:41.701,02:28:00
549,AI020,NaN,BOM,BLR,2026-04-19 03:53:41.701,2026-04-19 06:21:41.701,02:28:00
141,AI031,Air India,DEL,MAA,2026-04-20 13:05:41.701,2026-04-20 16:11:41.701,03:06:00
142,AI031,Air India,DEL,MAA,2026-04-20 13:05:41.701,2026-04-20 16:11:41.701,03:06:00
599,AI043,Air India,CCU,DEL,2026-04-19 00:28:41.701,2026-04-19 04:37:41.701,04:09:00
598,AI043,Air India,CCU,DEL,2026-04-19 00:28:41.701,2026-04-19 04:37:41.701,04:09:00
603,AI070,Air India,CCU,DEL,2026-04-19 00:05:41.702,2026-04-19 01:44:41.702,01:39:00
602,AI070,Air India,CCU,DEL,2026-04-19 00:05:41.702,2026-04-19 01:44:41.702,01:39:00
83,AI242,UNKNOWN,BLR,CCU,2026-04-20 16:41:41.704,2026-04-20 17:43:41.704,01:02:00
84,AI242,UNKNOWN,BLR,CCU,2026-04-20 16:41:41.704,2026-04-20 17:43:41.704,01:02:00
939,SJ037,SpiceJet,BLR,BOM,2026-04-17 19:14:41.701,2026-04-17 22:31:41.701,03:17:00
940,SJ037,SpiceJet,BLR,BOM,2026-04-17 19:14:41.701,2026-04-17 22:31:41.701,03:17:00
588,SJ118,SpiceJet,DEL,BOM,2026-04-19 01:08:41.702,2026-04-19 02:33:41.702,01:25:00
589,SJ118,SpiceJet,DEL,BOM,2026-04-19 01:08:41.702,2026-04-19 02:33:41.702,01:25:00
106,SJ142,SpiceJet,CCU,BOM,2026-04-20 15:14:41.702,2026-04-20 16:56:41.702,01:42:00
105,SJ142,SpiceJet,CCU,BOM,2026-04-20 15:14:41.702,2026-04-20 16:56:41.702,01:42:00
310,SJ146,SpiceJet,HYD,BLR,2026-04-19 22:37:41.702,2026-04-20 00:33:41.702,01:56:00
309,SJ146,SpiceJet,HYD,BLR,2026-04-19 22:37:41.702,2026-04-20 00:33:41.702,01:56:00
605,UK013,Vistara,BOM,MAA,2026-04-18 23:52:41.701,2026-04-19 02:52:41.701,03:00:00
606,UK013,Vistara,BOM,MAA,2026-04-18 23:52:41.701,2026-04-19 02:52:41.701,03:00:00
935,UK049,Vistara,HYD,BOM,2026-04-17 19:47:41.701,2026-04-17 20:32:41.701,00:45:00
936,UK049,Vistara,HYD,BOM,2026-04-17 19:47:41.701,2026-04-17 20:32:41.701,00:45:00
759,UK139,NaN,BLR,MAA,2026-04-18 10:54:41.703,2026-04-18 14:31:41.703,03:37:00
758,UK139,NaN,BLR,MAA,2026-04-18 10:54:41.703,2026-04-18 14:31:41.703,03:37:00
812,UK160,Vistara,BLR,BOM,2026-04-18 06:42:41.703,2026-04-18 10:58:41.703,04:16:00
813,UK160,Vistara,BLR,BOM,2026-04-18 06:42:41.703,2026-04-18 10:58:41.703,04:16:00
503,UK163,Vistara,DEL,HYD,2026-04-19 07:22:41.703,2026-04-19 09:04:41.703,01:42:00
502,UK163,Vistara,DEL,HYD,2026-04-19 07:22:41.703,2026-04-19 09:04:41.703,01:42:00
914,UK180,Vistara,CCU,MAA,2026-04-17 21:18:41.703,2026-04-17 23:29:41.703,02:11:00
915,UK180,Vistara,CCU,MAA,2026-04-17 21:18:41.703,2026-04-17 23:29:41.703,02:11:00

In [29]:
flights[flights["airline"].isna()]

,flight_id,airline,source,destination,departure_time,arrival_time,duration
57,UK209,NaN,MAA,BLR,2026-04-20 19:02:41.704,2026-04-20 21:47:41.704,02:45:00
63,6F270,NaN,HYD,MAA,2026-04-20 18:14:41.701,2026-04-20 19:02:41.701,00:48:00
89,UK224,NaN,CCU,MAA,2026-04-20 16:25:41.704,2026-04-20 20:24:41.704,03:59:00
118,6F261,NaN,CCU,DEL,2026-04-20 14:31:41.703,2026-04-20 17:29:41.703,02:58:00
120,6F254,NaN,MAA,BLR,2026-04-20 14:26:41.703,2026-04-20 18:01:41.703,03:35:00
124,6F259,NaN,BOM,DEL,2026-04-20 14:10:41.703,2026-04-20 15:21:41.703,01:11:00
133,UK141,NaN,HYD,MAA,2026-04-20 13:38:41.703,2026-04-20 15:59:41.703,02:21:00
150,6F255,NaN,DEL,BOM,2026-04-20 11:59:41.703,2026-04-20 15:33:41.703,03:34:00
218,AI047,NaN,CCU,MAA,2026-04-20 06:36:41.701,2026-04-20 07:23:41.701,00:47:00
222,AI128,NaN,BOM,CCU,2026-04-20 06:07:41.702,2026-04-20 10:03:41.702,03:56:00
225,SJ138,NaN,BLR,BOM,2026-04-20 05:55:41.702,2026-04-20 06:43:41.702,00:48:00
279,AI009,NaN,DEL,CCU,2026-04-20 01:31:41.701,2026-04-20 04:05:41.701,02:34:00
284,AI226,NaN,BLR,HYD,2026-04-20 01:19:41.703,2026-04-20 04:08:41.703,02:49:00
299,6F272,NaN,HYD,MAA,2026-04-19 23:35:41.702,2026-04-20 00:22:41.702,00:47:00
314,SJ099,NaN,MAA,BLR,2026-04-19 22:14:41.702,2026-04-20 00:34:41.702,02:20:00
319,6F260,NaN,CCU,DEL,2026-04-19 21:51:41.702,2026-04-20 01:14:41.702,03:23:00
351,6F271,NaN,HYD,MAA,2026-04-19 19:33:41.702,2026-04-19 22:52:41.702,03:19:00
357,6F256,NaN,BOM,CCU,2026-04-19 18:40:41.702,2026-04-19 19:13:41.702,00:33:00
376,AI252,NaN,HYD,DEL,2026-04-19 17:30:41.704,2026-04-19 21:54:41.704,04:24:00
395,SJ203,NaN,DEL,HYD,2026-04-19 16:22:41.703,2026-04-19 18:27:41.703,02:05:00
398,AI168,NaN,DEL,CCU,2026-04-19 15:50:41.703,2026-04-19 20:20:41.703,04:30:00
461,AI037,NaN,BOM,BLR,2026-04-19 11:14:41.701,2026-04-19 15:13:41.701,03:59:00
482,AI219,NaN,BLR,DEL,2026-04-19 09:28:41.703,2026-04-19 11:27:41.703,01:59:00
492,SJ051,NaN,BOM,BLR,2026-04-19 08:40:41.701,2026-04-19 12:18:41.701,03:38:00
549,AI020,NaN,BOM,BLR,2026-04-19 03:53:41.701,2026-04-19 06:21:41.701,02:28:00
550,AI020,NaN,BOM,BLR,2026-04-19 03:53:41.701,2026-04-19 06:21:41.701,02:28:00
562,AI243,NaN,BLR,BOM,2026-04-19 02:50:41.704,2026-04-19 05:09:41.704,02:19:00
630,UK081,NaN,BLR,DEL,2026-04-18 22:00:41.702,2026-04-18 23:00:41.702,01:00:00
658,UK088,NaN,MAA,BLR,2026-04-18 19:16:41.702,2026-04-18 23:36:41.702,04:20:00
664,SJ225,NaN,DEL,HYD,2026-04-18 18:16:41.704,2026-04-18 20:53:41.704,02:37:00
719,6F264,NaN,DEL,HYD,2026-04-18 14:03:41.701,2026-04-18 18:23:41.701,04:20:00
758,UK139,NaN,BLR,MAA,2026-04-18 10:54:41.703,2026-04-18 14:31:41.703,03:37:00
759,UK139,NaN,BLR,MAA,2026-04-18 10:54:41.703,2026-04-18 14:31:41.703,03:37:00
774,UK151,NaN,BOM,CCU,2026-04-18 10:11:41.703,2026-04-18 13:30:41.703,03:19:00
858,6F265,NaN,DEL,HYD,2026-04-18 02:27:41.703,2026-04-18 03:24:41.703,00:57:00
870,AI125,NaN,CCU,DEL,2026-04-18 01:12:41.702,2026-04-18 04:51:41.702,03:39:00
873,UK043,NaN,DEL,HYD,2026-04-18 00:48:41.701,2026-04-18 04:52:41.701,04:04:00
880,AI065,NaN,MAA,BLR,2026-04-18 00:09:41.701,2026-04-18 05:00:41.701,04:51:00
924,AI230,NaN,CCU,BLR,2026-04-17 20:37:41.704,2026-04-18 00:22:41.704,03:45:00
925,6F268,NaN,DEL,MAA,2026-04-17 20:29:41.701,2026-04-17 21:58:41.701,01:29:00
956,AI145,NaN,DEL,BOM,2026-04-17 17:06:41.702,2026-04-17 21:31:41.702,04:25:00

In [30]:
flights[flights["airline"] == "UNKNOWN"]

,flight_id,airline,source,destination,departure_time,arrival_time,duration
9,6F251,UNKNOWN,DEL,BLR,2026-04-20 22:56:41.703,2026-04-20 23:37:41.703,00:41:00
14,AI069,UNKNOWN,DEL,BOM,2026-04-20 22:43:41.702,2026-04-21 02:29:41.702,03:46:00
28,UK003,UNKNOWN,HYD,DEL,2026-04-20 21:41:41.700,2026-04-21 02:19:41.700,04:38:00
58,SJ043,UNKNOWN,MAA,DEL,2026-04-20 18:59:41.701,2026-04-20 21:08:41.701,02:09:00
83,AI242,UNKNOWN,BLR,CCU,2026-04-20 16:41:41.704,2026-04-20 17:43:41.704,01:02:00
84,AI242,UNKNOWN,BLR,CCU,2026-04-20 16:41:41.704,2026-04-20 17:43:41.704,01:02:00
90,UK077,UNKNOWN,HYD,BOM,2026-04-20 16:22:41.702,2026-04-20 18:00:41.702,01:38:00
148,AI222,UNKNOWN,BOM,DEL,2026-04-20 12:10:41.703,2026-04-20 13:14:41.703,01:04:00
189,AI044,UNKNOWN,MAA,BLR,2026-04-20 09:03:41.701,2026-04-20 12:36:41.701,03:33:00
209,UK229,UNKNOWN,HYD,DEL,2026-04-20 07:40:41.704,2026-04-20 11:57:41.704,04:17:00
220,AI088,UNKNOWN,MAA,DEL,2026-04-20 06:34:41.702,2026-04-20 10:10:41.702,03:36:00
253,6F250,UNKNOWN,DEL,BLR,2026-04-20 03:26:41.701,2026-04-20 07:30:41.701,04:04:00
270,6F250,UNKNOWN,CCU,BLR,2026-04-20 02:23:41.702,2026-04-20 02:56:41.702,00:33:00
304,SJ029,UNKNOWN,HYD,DEL,2026-04-19 22:55:41.701,2026-04-20 00:22:41.701,01:27:00
394,6F253,UNKNOWN,MAA,BLR,2026-04-19 16:26:41.703,2026-04-19 18:24:41.703,01:58:00
418,AI100,UNKNOWN,CCU,BOM,2026-04-19 14:42:41.702,2026-04-19 18:22:41.702,03:40:00
443,SJ027,UNKNOWN,BOM,MAA,2026-04-19 12:50:41.701,2026-04-19 17:13:41.701,04:23:00
507,6F263,UNKNOWN,DEL,HYD,2026-04-19 07:07:41.703,2026-04-19 08:30:41.703,01:23:00
533,AI046,UNKNOWN,DEL,BOM,2026-04-19 05:09:41.701,2026-04-19 08:00:41.701,02:51:00
578,6F262,UNKNOWN,MAA,DEL,2026-04-19 01:44:41.702,2026-04-19 02:47:41.702,01:03:00
580,6F269,UNKNOWN,HYD,MAA,2026-04-19 01:30:41.702,2026-04-19 02:52:41.702,01:22:00
640,AI250,UNKNOWN,BOM,CCU,2026-04-18 20:48:41.704,2026-04-19 00:12:41.704,03:24:00
677,UK112,UNKNOWN,CCU,DEL,2026-04-18 17:05:41.702,2026-04-18 19:47:41.702,02:42:00
693,6F257,UNKNOWN,MAA,CCU,2026-04-18 16:04:41.704,2026-04-18 19:55:41.704,03:51:00
709,6F252,UNKNOWN,MAA,BLR,2026-04-18 14:25:41.701,2026-04-18 18:52:41.701,04:27:00
765,SJ140,UNKNOWN,HYD,DEL,2026-04-18 10:42:41.702,2026-04-18 14:30:41.702,03:48:00
768,SJ096,UNKNOWN,DEL,HYD,2026-04-18 10:29:41.702,2026-04-18 13:45:41.702,03:16:00
780,6F266,UNKNOWN,CCU,MAA,2026-04-18 09:49:41.703,2026-04-18 11:17:41.703,01:28:00
794,6F267,UNKNOWN,DEL,MAA,2026-04-18 07:56:41.703,2026-04-18 11:49:41.703,03:53:00
933,SJ212,UNKNOWN,MAA,BLR,2026-04-17 19:49:41.703,2026-04-17 21:44:41.703,01:55:00
996,6F258,UNKNOWN,BOM,DEL,2026-04-17 13:54:41.703,2026-04-17 16:49:41.703,02:55:00

In [31]:
flights["source"].value_counts(dropna=False)

source
BOM    207
HYD    180
CCU    174
DEL    163
MAA    157
BLR    139
Name: count, dtype: int64

In [32]:
flights["destination"].value_counts(dropna=False)

destination
DEL    200
CCU    188
BOM    174
BLR    165
MAA    151
HYD    142
Name: count, dtype: int64

In [33]:
flights[["departure_time", "arrival_time"]].head(10)

           departure_time            arrival_time
0 2026-04-20 23:38:41.701 2026-04-21 02:32:41.701
1 2026-04-20 23:35:41.703 2026-04-21 01:23:41.703
2 2026-04-20 23:26:41.702 2026-04-21 01:11:41.702
3 2026-04-20 23:07:41.704 2026-04-21 01:43:41.704
4 2026-04-20 23:05:41.703 2026-04-21 04:04:41.703
5 2026-04-20 23:05:41.703 2026-04-21 01:24:41.703
6 2026-04-20 23:04:41.703 2026-04-21 00:47:41.703
7 2026-04-20 23:03:41.702 2026-04-21 00:35:41.702
8 2026-04-20 23:02:41.701 2026-04-20 23:57:41.701
9 2026-04-20 22:56:41.703 2026-04-20 23:37:41.703

In [34]:
departure = pd.to_datetime(flights["departure_time"], errors="coerce")
arrival = pd.to_datetime(flights["arrival_time"], errors="coerce")

In [35]:
print("Invalid departure times:", departure.isna().sum())
print("Invalid arrival times:", arrival.isna().sum())

Invalid departure times: 0
Invalid arrival times: 0

In [36]:
flights[arrival < departure][
    ["flight_id", "departure_time", "arrival_time", "duration"]
]

    flight_id      departure_time        arrival_time             duration
355     SJ192 2026-04-19 18:45:42 2026-04-18 23:45:42  1899-12-29 05:00:00

In [37]:
calculated_duration = arrival - departure

In [38]:
calculated_duration.head()

0   0 days 02:54:00
1   0 days 01:48:00
2   0 days 01:45:00
3   0 days 02:36:00
4   0 days 04:59:00
dtype: timedelta64[us]

In [39]:
comparison = flights[
    ["flight_id", "departure_time", "arrival_time", "duration"]
].copy()

comparison["calculated_duration"] = calculated_duration

comparison.head(10)

,flight_id,departure_time,arrival_time,duration,calculated_duration
0,SJ010,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701,02:54:00,0 days 02:54:00
1,AI155,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703,01:48:00,0 days 01:48:00
2,UK094,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702,01:45:00,0 days 01:45:00
3,AI245,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704,02:36:00,0 days 02:36:00
4,AI192,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703,04:59:00,0 days 04:59:00
5,SJ158,2026-04-20 23:05:41.703,2026-04-21 01:24:41.703,02:19:00,0 days 02:19:00
6,6F196,2026-04-20 23:04:41.703,2026-04-21 00:47:41.703,01:43:00,0 days 01:43:00
7,AI080,2026-04-20 23:03:41.702,2026-04-21 00:35:41.702,01:32:00,0 days 01:32:00
8,6F025,2026-04-20 23:02:41.701,2026-04-20 23:57:41.701,00:55:00,0 days 00:55:00
9,6F251,2026-04-20 22:56:41.703,2026-04-20 23:37:41.703,00:41:00,0 days 00:41:00

In [40]:
missing_passengers = ~bookings["passenger_id"].isin(
    passengers["passenger_id"]
)

missing_passengers.sum()

np.int64(0)

In [41]:
missing_flights = ~bookings["flight_id"].isin(
    flights["flight_id"]
)

missing_flights.sum()

np.int64(0)